apiVersion: v1
kind: Service
metadata:
  name: talent-api-service
  namespace: talent-app
spec:
  selector:
    app: talent-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer