apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: talent-app
type: Opaque
stringData:
  PORT: "5000"
  DATABASE_URL: "postgresql://postgres:postgres123@postgres-service:5432/talentdb"